// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ABackTop: typeof import('ant-design-vue/es')['BackTop']
    ABadgeRibbon: typeof import('ant-design-vue/es')['BadgeRibbon']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACol: typeof import('ant-design-vue/es')['Col']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    APageHeader: typeof import('ant-design-vue/es')['PageHeader']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATag: typeof import('ant-design-vue/es')['Tag']
    Card: typeof import('./src/components/Card.vue')['default']
    ECharts: typeof import('./src/components/ECharts.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VideoCard: typeof import('./src/components/VideoCard.vue')['default']
  }
}
